#!/bin/sh

# Bind-mount userdata over to /data on the rootfs
[ -e "$rootfs_location/data" ] || mkdir "$rootfs_location/data"
mount --bind $rootfs_par "$rootfs_location/data"

# Prefer /sbin/preinit as hybris-boot normally runs this
[ -e "$rootfs_location/sbin/preinit" ] && init="$rootfs_location/sbin/preinit"
