#!/bin/sh

# Bind-mount userdata over to /data on the rootfs
droid_data="$rootfs_location/data"
[ -e "$droid_data" ] || mkdir "$droid_data"
mount --bind $rootfs_par "$droid_data"

# Prefer /sbin/preinit as hybris-boot normally runs this
[ -e "$rootfs_location/sbin/preinit" ] && init="$rootfs_location/sbin/preinit"
